### ISSUE TITLE
Identifier incorrectly resolved to type in std:: package

### ISSUE THREAD

**Issue by gezalore** [verilator/verilator#4682] opened 2023-11-10 16:50 UTC
Trying to compile the following:

```systemverilog
module top;
   reg process = 1;
   initial $display(process);
endmodule
```

Produces this error:

```
%Error: process.sv:3:7: syntax error, unexpected TYPE-IDENTIFIER
    3 |   reg process = 1;
      |       ^~~~~~~
```

I suspect it's resolving to `class std::process`, but I did not dig into it.

**Comment by wsnyder** [comment] 2023-11-10 17:31
This is effectively a duplicate of #2412

**Closed by wsnyder** 2023-11-10 17:31 UTC
Labels: resolution: duplicate
