### ISSUE TITLE
Unique inside case with --assert gives Unsupported: RHS of ==? or !=? must be constant to be synthesizable

### ISSUE THREAD

**Issue by hdzhangdoc** [verilator/verilator#2199] opened 2020-03-24 09:38 UTC
Hello，we met a problem with systemverilog‘s "unique case“ statement，hope your help：
![image](https://user-images.githubusercontent.com/43007864/77410618-1af70480-6df6-11ea-86c8-873dffb73257.png)

source code is like below：
![image](https://user-images.githubusercontent.com/43007864/77410693-3eba4a80-6df6-11ea-9c47-f91f29d0b136.png)

Could you help to solve it？Thanks

**Comment by wsnyder** [comment] 2020-03-24 11:34
The base error is something correctly unsupported, but it looks like the optimizer is doing something wrong in this case to get that message.

I'll need a standalone test that reproduces it to debug further, ideally in test_regress format.  

P.S. Attaching at least the error message as text instead of a screenshot would be make this a bit easier, as can cut & paste.

**Comment by hdzhangdoc** [comment] 2020-03-26 06:58
I'm sorry for that I didn't provide some src code， please check it below which the error exists in. Does it can help？

**Comment by hdzhangdoc** [comment] 2020-03-26 07:02
And another similar error occur，source code attached

![image](https://user-images.githubusercontent.com/43007864/77619227-bad99d00-6f72-11ea-9960-a951547f99b2.png)

**Comment by hdzhangdoc** [comment] 2020-03-26 07:02
[dm_csrs.zip](https://github.com/verilator/verilator/files/4385524/dm_csrs.zip)

**Comment by hdzhangdoc** [comment] 2020-03-26 07:03
[riscv_decoder.zip](https://github.com/verilator/verilator/files/4385527/riscv_decoder.zip)

**Comment by wsnyder** [comment] 2020-03-26 12:23
By example, I mean please provide something standalone and smallish which when I type "make" gives the error.  What you attached are not complete.  Also please try to remove whatever code is not relevant (that is you still get the error after removing). Thanks

**Comment by hdzhangdoc** [comment] 2020-03-26 12:41
my project is very huge， it perhaps will spend long time to simplify the project..

**Comment by hdzhangdoc** [comment] 2020-03-30 04:43
[verilator_riscv_test.zip](https://github.com/verilator/verilator/files/4400818/verilator_riscv_test.zip)
Please help，thanks

**Comment by wsnyder** [comment] 2020-03-30 22:16
Thanks, was able to reduce the test case. The key thing to get the error was --assert.

Fixed in git towards 4.032.

**Closed by wsnyder** 2020-03-30 22:16 UTC
Labels: resolution: fixed
