### ISSUE TITLE
Is $bits(interface.port) supported?

### ISSUE THREAD

**Issue by nanduraj1** [verilator/verilator#2085] opened 2019-12-31 18:54 UTC
### Test Code
```systemverilog
interface t_if #(
    parameter D_WIDTH=8
);

    logic [D_WIDTH-1:0]  data;

    modport source (output data);
    modport sink   (input  data);
endinterface


module test(
    t_if.sink snk_if
);

    localparam D_WIDTH = $bits(snk_if.data); // This throws error
    // localparam D_WIDTH = snk_if.D_WIDTH; // This Works

endmodule

// Top Module
module t();

    t_if #(.D_WIDTH(64)) snk_if();

    test test_inst(.*);

endmodule
```
### Error
`localparam D_WIDTH = $bits(snk_if.data);` gives error **Parameter-resolved constants must not use dotted references: 'data'**

### Question

`$bits(snk_if.data)` works on questa and quartus, but not on verilator.  Is this not an unnecessary feature? If so, can it be added easily?

**Comment by nndurj** [comment] 2020-01-01 03:02
Same as this? #1593

**Comment by nanduraj1** [comment] 2020-01-01 03:06
Duplicate Issue

**Comment by nndurj** [comment] 2020-01-01 06:21
Related #1646 , #1593

**Comment by wsnyder** [comment] 2020-01-09 23:10
Thanks for the report, as you found, this is a duplicate of #1593.

**Closed** 2020-01-09 23:10 UTC
Labels: area: elaboration, resolution: duplicate
