### ISSUE TITLE
Linear arrangement of wait statements results in timeout

### ISSUE THREAD

**Issue by kiryk** [verilator/verilator#4197] opened 2023-05-12 11:36 UTC
When working on a branch, I made a test where I chained 4 `initial` blocks so that all but the first one await for its predecessor and then print some message. The verilated design timeouts and doesn't produce correct output both on my and the master branch.

Interestingly, if the chain is reduced to 3 blocks, the simulation works.

Here is the test: [t_process_await.zip](https://github.com/verilator/verilator/files/11463507/t_process_await.zip).

Tested on the current master; on Fedora, Linux 6.1.14

**Comment by kbieganski** [comment] 2023-05-19 08:55
Currently, event-triggered coroutines live in two stages: _uncommitted_ and _ready_. First they land in _uncommitted_, meaning they can't be resumed yet. Only after coroutines from the _ready_ queue are resumed, the _uncommitted_ ones are moved to the _ready_ queue, and are able to be resumed. This is to avoid self triggering in situations like:
```systemverilog
event e;
->e;
@e;
```
This works fine. The issue is with `wait` statements. If you have:
```systemverilog
wait(b);
```
this is translated to something like:
```systemverilog
while (!b)
    @b;
```
If `b` is false at first, the coroutine is put into the `uncommitted` queue. If `b` is set to true before it's committed, the coroutine won't get resumed.

I have a fix [here](https://github.com/antmicro/verilator-1/commit/be906a31d1bcf707fc226ea35c6eac1bdf19323d). It basically just immediately commits coroutines that `wait`. I'll submit a PR next week, as I'm not yet sure this is the cleanest way to do it.

**Closed** 2023-05-26 00:20 UTC
Labels: status: assigned
