### ISSUE TITLE
ALWCOMBORDER - Clause b of Section 9.2.2.2.1 is ignored

### ISSUE THREAD

**Issue by erankit9** [verilator/verilator#4052] opened 2023-03-20 15:48 UTC
ALWCOMBORDER - "Warning is reported" during verilator build for always_comb usage. In below scenario, the variable on the left hand side should be ignored (add to exception list) for this warning and should not be part of sensitive list even if it is used on the right hand side for the calculation, as this is getting assigned during this block execution.

Warning: %Warning-ALWCOMBORDER:  Always_comb variable driven after use: 'a'

Problem code:
```
module demo();

logic [3:0] a;
logic [3:0] b;
bit [3:0] r;
logic clk;
always @(posedge clk) 
begin
    r<=a;
    $display("Demo value A %p \n", a);
    $display("Demo value R %p \n", r);
end
always_comb begin
    $display("Combo value A %p \n", a);
    if (a<4) begin
        a = r + 1'b1;
        $display("Combo a< 4 value A %p \n", a);
    end
    else begin
        a = 1;
        $display("Combo else value A %p \n", a);
    end
end
initial begin
    clk = 0;
    repeat(10) begin 
        #1;
        clk = ~clk;
    end
end
endmodule.
```

Spec Snapshot:

What 'verilator --version' are you using?  Did you try it with the git master version? : Verilator 5.006 2023-01-22 rev v5.006 , Yes

May we assist you in trying to fix this in Verilator yourself : Yes

<img width="601" alt="SV_SPEC" src="https://user-images.githubusercontent.com/128394914/226393837-8e103419-b599-4b1b-87f0-dd5b45e74205.png">

**Comment by udif** [comment] 2023-03-20 16:04
I don't understand your point.
Your code has a combinatorial loop.
a's value depends on whether (a<4) or not.
What "exception list" are you talking about?

If you are trying to build something that counts from 1 to 4 and loops back to 1, this is definitely not the way.

**Comment by udif** [comment] 2023-03-20 19:28
The problem is that instead of taking the hint from the tool that your coding style is causing combinatorial loops, and won't behave as you expect when it is synthesized, you try to argue that this should not trigger a warning.
I assume you are new to Verilog and HDLs in general?

**Comment by erankit9** [comment] 2023-03-20 19:35
We are trying to incorporate the usage of verilator as an alternative of vcs. As per the exception captured in 9.2.2.2.1, this scenario should not be considered as "Warning". I believe this is not about the coding style but it is more about following the spec. Just fyi : VCS is not showing this as warning.

**Comment by udif** [comment] 2023-03-20 20:29
As the Verilator documentation says, you can ignore the warning if you like.
```
ALWCOMBORDER
Warns that an always_comb block has a variable that is set after it is used.
This may cause simulation-synthesis mismatches, as not all simulators allow this ordering.

always_comb begin
   a = b;
   b = 1;
end

Ignoring this warning will only suppress the lint check; it will simulate correctly.
```
The fact that VCS is not showing you a warning merely implies that VCS only worries about the legality of the code (it is).
The Verilator warning is not because the code is illegal, but because it is a hint that it is probably not what you expect.

I see you use VCS. Have you tried running your code through Spyglass ? It will probably warn you on the same lines.

**Comment by wsnyder** [comment] 2023-03-20 22:04
Verilator is by design not intended to do exactly what IEEE requires, but instead be fast on code that is well designed (e.g. does not have combo logic loops). I don't think we are likely to change how the message works, as its implementation is in sync with how it does always blocks now, which is what Verilator is designed to optimize well.  If you want to propose new text for the ALWCOMBORDER documentation to describe how this differs from IEEE or otherwise clarify that would be welcome.

**Comment by wsnyder** [comment] 2023-04-02 20:34
Closing as described above - welcome a pull to improve documentation if you would like to do so.

**Closed** 2023-04-02 20:34 UTC
Labels: area: lint, resolution: wontfix
