### ISSUE TITLE
Duplicate symbol in archive file

### ISSUE THREAD

**Issue by ombre5733** [verilator/verilator#4513] opened 2023-09-21 14:24 UTC
I'm using verilator for some third party design. Unfortunately, the final linking step stops with an error because a symbol (the function `Vdecap_with_support_tb___024root___eval_initial__TOP__0`) is defined multiple times.

In file `Vdecap_with_support_tb___024root__DepSet_h6dde8dea__0__Slow.cpp` I found the following implementation:

    VL_ATTR_COLD void Vdecap_with_support_tb___024root___eval_initial__TOP__0(Vdecap_with_support_tb___024root* vlSelf) {
        if (false && vlSelf) {}  // Prevent unused
        Vdecap_with_support_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
        VL_DEBUG_IF(VL_DBG_MSGF("+    Vdecap_with_support_tb___024root___eval_initial__TOP__0\n"); );
        // Body
       ... here comes the initialization of a RAM block ...
    }

In the file `Vdecap_with_support_tb___024root__DepSet_h6dde8dea__1__Slow.cpp` there is another definition of the same function:

    VL_ATTR_COLD void Vdecap_with_support_tb___024root___eval_initial__TOP__0(Vdecap_with_support_tb___024root* vlSelf) {
        if (false && vlSelf) {}  // Prevent unused
        Vdecap_with_support_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
        VL_DEBUG_IF(VL_DBG_MSGF("+    Vdecap_with_support_tb___024root___eval_initial__TOP__0\n"); );
        // Init
        IData/*31:0*/ __Vilp;
        // Body
        Vdecap_with_support_tb___024root___eval_initial__TOP__0(vlSelf);
        vlSelf->__Vm_traceActivity[0xdU] = 1U;
        vlSelf->__Vm_traceActivity[0xcU] = 1U;
        vlSelf->__Vm_traceActivity[0xbU] = 1U;
        vlSelf->__Vm_traceActivity[0xaU] = 1U;
        vlSelf->__Vm_traceActivity[9U] = 1U;
        vlSelf->__Vm_traceActivity[8U] = 1U;
        vlSelf->__Vm_traceActivity[7U] = 1U;
        vlSelf->__Vm_traceActivity[6U] = 1U;
        vlSelf->__Vm_traceActivity[5U] = 1U;
        vlSelf->__Vm_traceActivity[4U] = 1U;
        vlSelf->__Vm_traceActivity[3U] = 1U;
        vlSelf->__Vm_traceActivity[2U] = 1U;
        vlSelf->__Vm_traceActivity[1U] = 1U;
        vlSelf->__Vm_traceActivity[0U] = 1U;
        ... initialization of more registers ...
    }

The implementation in `...__1__Slow.cpp` looks very suspicuous to me since this is an unguarded recursive call to the function.
I tried to look at the verilator source code to understand how it generates the name of the `eval_initial` functions but do not know, where the final index comes from.

Unfortunately, the project that I'm using verilator on is quite convoluted so I have not been able to extract a reproducer. I would need some hints to know where to actually look for the problem.

Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)

**not yet**

What 'verilator --version' are you using?  Did you try it with the git master version?

**Verilator 5.014 2023-08-06 rev v5.014**
**Did not try git master, yet**

What OS and distribution are you using?

**Rocky Linux release 8.8 (Green Obsidian)**

May we assist you in trying to fix this in Verilator yourself?

**yes**

**Comment by wsnyder** [comment] 2023-09-21 14:29
I suspect is duplicate of https://github.com/verilator/verilator/issues/4416 which was fixed last release, can you confirm?

**Closed** 2023-09-25 02:09 UTC
Labels: resolution: duplicate

**Comment by ombre5733** [comment] 2023-09-25 06:26
Took me a while to integrate the new verilator version into our toolchain. Can confirm that the bug is indeed resolved in v5.016.
