### ISSUE TITLE
A issue of blocking and non-blocking assignment of logic types.

### ISSUE THREAD

**Issue by jswtyc** [verilator/verilator#5256] opened 2024-07-12 15:37 UTC
I am a professional in the FPGA industry.
And in Vivado, it is legal to assign logic variables through both blocking and non blocking methods, as shown in the following code.

                  module test(
                      input clk,
                      input [1:0] a,
                      output logic [1:0] b
                      );
                  assign b[0] = a[0];
                  always_ff @ (posedge clk)
                      b[1] <= a[1];
                  endmodule

I don't know if this approach is legal in IC design, so I can't be sure if it's a bug or a feature.
Any response will be appreciated.

**Comment by jswtyc** [comment] 2024-07-12 15:50
![figure_verilator](https://github.com/user-attachments/assets/5520035a-9255-44b1-b8b8-13c02f34135d)

**Comment by jswtyc** [comment] 2024-07-12 15:53
![image](https://github.com/user-attachments/assets/da9d2daa-dbfa-4f1d-9fa6-7f5cf832856a)
The same code in Vivado, no error worning and bugs.

**Comment by wsnyder** [comment] 2024-07-12 16:37
Please see the documentation the error refers to https://veripool.org/guide/latest/warnings.html#cmdoption-arg-BLKANDNBLK

Closing as answered but feel free to follow up if that is not clear.

**Closed as completed by wsnyder** 2024-07-12 16:37 UTC
Labels: resolution: answered

**Comment by jswtyc** [comment] 2024-07-13 04:22
> Please see the documentation the error refers to https://veripool.org/guide/latest/warnings.html#cmdoption-arg-BLKANDNBLK
> 
> Closing as answered but feel free to follow up if that is not clear.

Thank you, buddy, but I still believe that since it is legal, a warning should be issued during Linter's inspection instead of an error.

**Comment by wsnyder** [comment] 2024-07-13 10:29
I can appreciate your position is reasonable, but the problem is people often ignore warnings, and if the code can't run through Verilator non-lint also successfully, that needs to be an error that can't be ignored.   Verilator lint is intended to show Verilator compatibility, not specifically and as a strict set IEEE compliance.   There are closed-source tools that are closer to that and might be a better fit if that is what you want, though all still have some vendor-related restrictions and are not just IEEE-only AFAIK.
