### ISSUE TITLE
Spurious comparison is constant warning

### ISSUE THREAD

**Issue by alexforencich** [verilator/verilator#3049] opened 2021-06-29 21:21 UTC
Verilator is giving me a spurious linter warning on some unreachable code:

    %Warning-CMPCONST: ../../rtl/dma_if_pcie_us_rd.v:863:49: Comparison is constant due to limited range
                                                           : ... In instance dma_if_pcie_us_rd
      863 |                         if (op_dword_count_next > (AXIS_PCIE_DATA_WIDTH/32-3)) begin
          |                                                 ^

The code in question is inside this if statement, and as such is unreachable with the parameter value that results in the constant comparison:

    if (AXIS_PCIE_DATA_WIDTH > 64) begin

The module in question: https://github.com/alexforencich/verilog-pcie/blob/master/rtl/dma_if_pcie_us_rd.v

Edit: this is the case as of Verilator 4.202.

**Comment by wsnyder** [comment] 2021-06-29 23:47
Thanks for the good report writeup. The warning is different but this is a duplicate of #2866.

**Closed by wsnyder** 2021-06-29 23:47 UTC
Labels: resolution: duplicate
