### ISSUE TITLE
2D array in `generate if` construct lint failure 

### ISSUE THREAD

**Issue by sliv2001** [verilator/verilator#4891] opened 2024-02-12 08:22 UTC
Hi!

I encountered the lint-time bug in following case:

```bash
verilator --lint-only ./failing_module.v
```

```Verilog
// failing_module.v
module mod;

  localparam int Array[2][3] = '{'{2, 3, 4}, '{5, 6, 7}}; // parameter is also bugous
  int s;
  generate
    if (1 >= Array[0][0])
    begin:g_f
      assign s=1;
    end
  endgenerate

endmodule : mod
```

Variable `s` is just for filling of `if` block. Problem is in 2D array. Verilator complains as follows:

```txt
%Error: failing_module.v:7:14: Expecting expression to be constant, but variable isn't const: 'Array'
                             : ... In instance mod
    7 |     if (1 >= Array[0][0])
      |              ^~~~~
%Error: failing_module.v:7:11: Generate If condition must evaluate to constant
                             : ... In instance mod
    7 |     if (1 >= Array[0][0])
      |           ^~
%Error: Exiting due to 2 error(s)
```

2D Array is actually constant (localparam), but seems that either `Array` cannot be constified, or even parsing of 2D arrays fail.

The bug appears for git master branch, at both MacOS and Linux Ubuntu.

**Comment by wsnyder** [comment] 2024-02-12 12:34
Thanks for the well written report, this is a duplicate of #2272.  Perhaps you'd consider submitting a pull request to improve this?  If so please comment in #2272, thanks!

**Closed by wsnyder** 2024-02-12 12:34 UTC
Labels: area: elaboration, resolution: duplicate
