### ISSUE TITLE
Verilator confuses type with argument to task

### ISSUE THREAD

**Issue by treforsouthwell** [verilator/verilator#2956] opened 2021-05-13 14:35 UTC
This code builds with Cadence Xrun and Synopsys VCS but fails on Verilator.

I think it's applying the earlier typedef to the input name on the task.

./verilator --version
Verilator 4.200 2021-03-12 rev v4.110-43-g5022e81af (mod)

./verilator -sv -cc test.sv
%Error: test.sv:7:54: syntax error, unexpected TYPE-IDENTIFIER, expecting IDENTIFIER or randomize
    7 |       inout  STYPE                                   line ;
      |                                                      ^~~~
%Error: Exiting due to 1 error(s)

-- test.sv --
package fred;

typedef string STYPE;
typedef string line;

task automatic testf;
      inout  STYPE                                   line ;
      input  bits;
endtask

endpackage
module top;

endmodule

**Comment by wsnyder** [comment] 2021-05-13 14:50
This is a duplicate of #2412. Note #2412 is unlikely to get fixed short term, you'll need to edit this code, sorry.

**Closed by wsnyder** 2021-05-13 14:50 UTC
Labels: resolution: duplicate
