### ISSUE TITLE
Please use -std=c++NN

### ISSUE THREAD

**Issue by yurivict** [verilator/verilator#4652] opened 2023-11-01 07:19 UTC
Verilator currently builds w/out -std=c++NN, which means that a default C++ standard level is used that the C++ compiler currently has.

SystemC also builds w/out -std=c++NN, but it was built with C++14 standard for some reason, which caused https://github.com/verilator/verilator/issues/4499

To avoid such problems all projects should use -std=c++NN, and in case of Verilator these should match.

**Comment by wsnyder** [comment] 2023-11-01 11:55
Verilator won't be adding --std by default. We tried that and it broke a lot of systems.  The problem is similar to what's leading you here - without knowing how libraries were compiled adding a different --std tends to break things.  So we only add --std when we have to for compilation to work. While not ideal (e.g. your case) this has proven much more stable than adding --std.  You are of course free to './configure CXX="g++ -std=FOO"'  if you prefer to do so yourself.

**Closed by wsnyder** 2023-11-01 11:55 UTC
Labels: resolution: wontfix
