### ISSUE TITLE
protect_lib and gated clock

### ISSUE THREAD

**Issue by fuyong10** [verilator/verilator#2169] opened 2020-02-14 11:32 UTC
For testing gated clock purpose, I modified secret_impl.v under make_protect_lib example:

     always @(posedge clk) begin
changed to:
     wire GC = clk & a[0];
     always @(posedge GC) begin

Compile error. Seems like obj_dir_secret/verilated_secret.sv is not generated correctly:

    // Evaluate clock edges
    always @( ) begin   <==== sensitive list is empty.

**Comment by toddstrader** [comment] 2020-02-14 13:00
Yeah, that definitely sounds like a --protect-lib code generation bug.  Do you want to make a PR for a new test in `test_regression` and/or a fix for this?  If not, I can take a look.

**Comment by fuyong10** [comment] 2020-02-14 23:19
I am quite new to Verilator so really not capable of fixing yet. Please go ahead and take a look.

Ps, what does "PR" here mean?

**Comment by Millennium-Software-Design** [comment] 2020-02-15 02:17
PR: Pull Request.  See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

(in the good ol' days we just said, "patch")

**Comment by toddstrader** [comment] 2020-02-18 22:54
Test is in branch:
https://github.com/verilator/verilator/tree/issue-2169

I'll look into a fix next.

**Comment by toddstrader** [comment] 2020-02-20 10:43
As with most things this turns out to be more complicated than I originally anticipated.  I'm still working on the solution, but what's clear to me now is that if you're concerned about performance you'll want to do your clock gating outside of the --protect-lib modules.  See the manual for its advice on clock enables and clocker/clock_enable attributes.

**Comment by toddstrader** [comment] 2020-02-24 11:37
Resolved in #2172.

**Closed** 2020-02-24 11:36 UTC
Labels: type: bug
